#BTT decides what request to make to get the position of the p/g/r switch
#BPT decides what request to make for the BP pressure
#BCT decides what request to make for the BC pressure
#they're relevant only for the first query as we will make a subscription for the updates
PressureUnit = [ "Pressure_BAR_G", "Pressure_PSI_G"]
    
VehicleData = {
    "BR101" : { 
        "Weight": 84,
        "BTT": 6,
        "BPT": 2, # BP = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/BP (AirPipe).Pressure_BAR_G", headers = header).json())
        "BCT": 2, #BC = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/BrakeCylinder_1.Pressure_BAR_G", headers = header).json() 
        "isWagon": False,
        "DiType" : 0,
        },
    "OBB1020" : { 
        "Weight": 120,
        "BTT" : 7,
        "BPT" : 1, # BP = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/AirPipe (BP).Pressure_BAR_G", headers = header).json()
        "BCT" : 5, #     BC = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/Brake Cylinder Volume A.Pressure_BAR_G", headers = header).json() 
        "isWagon": False,
        "DiType" : 0,
    },
    "BR103" : {
        "Weight": 114,
        "BTT": 5, #BrakeMode 
        "BPT": 3, # BP = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/HL.Pressure_BAR_G", headers = header).json() 
        "BCT": 3, # BC = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/BrakeCylinder2.Pressure_BAR_G", headers = header).json() 
        "isWagon": False,
        "DiType" : 0,
    },
    "BR110" : {
        "Weight": 85,
        "BTT": 5,
        "BPT": 3,
        "BCT": 3,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR111" : {
        "Weight": 85,
        "BTT": 5,
        "BPT": 3,
        "BCT": 3,
        "isWagon": False,
        "DiType" : 0,
    },
    "OBB1116": {
        "Weight": 88,
        "BTT": 8,
        "BPT": 2,  
        "BCT": 1, # BC = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/BrakeCylinder.Pressure_BAR_G", headers = header).json() 
        "isWagon": False,
        "DiType" : 0,
    },
    "BR112" : {
        "Weight": 82.5,
        "BTT": 10, #BrakeMode_F
        "BPT": 1,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR114" : {
        "Weight": 82.5,
        "BTT": 5,
        "BPT": 1,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR140" : {
        "Weight" : 83,
        "BTT" : 5,
        "BPT" : 3,
        "BCT" : 3,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR143" : {
        "Weight": 82.5,
        "BTT": 5,
        "BPT": 1,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "DB146": {
        "Weight": 85,
        "BTT": 3,
        "BPT": 2,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR146-2": {
        "Weight": 85,
        "BTT": 3,
        "BPT": 2,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR155" : {
        "Weight": 123,
        "BTT": 4,  #BrakeMode_Switch 
        "BPT": 1,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR182" : {
        "Weight": 86,
        "BTT": 8,
        "BPT": 2,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR185" : {
        "Weight": 85,
        "BTT": 3,
        "BPT": 2,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR185-2" : {
        "Weight": 85,
        "BTT": 3,
        "BPT": 2,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR185-5" : {
        "Weight": 85,
        "BTT": 8,
        "BPT": 2,
        "BCT": 2,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR187" : {
        "Weight": 85,
        "BTT": -1,
        "BPT": 2,
        "BCT": 2,
        "isWagon": False,
        "DiType" : 0,

    },
    "Vectron" : {
        "Weight": 90,
        "BTT": 3,
        "BPT": 2,
        "BCT": 4, # BC = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/BrakeCylinder_1_2.Pressure_BAR_G", headers = header).json() 
        "isWagon": False,
        "DiType" : 0,
    },
    "BR194" : {
        "Weight": 120,
        "BTT": 7,
        "BPT": 1,
        "BCT": 5,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR204" : {
        "Weight": 70,
        "BTT": -1,
        "BPT": 1,
        "BCT": 2,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR218" : {
        "Weight": 80,
        "BTT": 5,
        "BPT": 3,
        "BCT": 3,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR294" : {
        "Weight": 85,
        "BTT": 5,
        "BPT": 1,
        "BCT": 1,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR363" : {
        "Weight": 55,
        "BTT": -1,
        "BPT": 1,
        "BCT": 2,
        "isWagon": False,
        "DiType" : 0,
    },
    "BR365" : {
        "Weight": 55,
        "BTT": -1,
        "BPT": 1,
        "BCT": 2,
        "isWagon": False,
        "DiType" : 0,
    },
    "E94" : {
        "Weight": 120,
        "BTT": 7,
        "BPT": 1,
        "BCT": 5,
        "isWagon": False,
        "DiType" : 0,
    },
    "G6" : {
        "Weight": 65,
        "BTT": -1,
        "BPT": 1,
        "BCT": 6, # /get/CurrentFormation/0/Simulation/Bremszylinder1.Pressure_BAR_G
        "isWagon": False,
        "DiType" : 0,
    },
    "Eanos" : {
        "Weight": 26,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 4,
    },
    "Es050" : {
        "Weight": 11,
        "BTT": 2, # PassengerGoodsValve
        "BPT": 1,
        "BCT": 7, #BC = request.get(tswapi + "/get/CurrentFormation/" + str(i) + "/Simulation/BrakeCylinder_2.Pressure_BAR_G", headers = header).json() 
        "isWagon": True,
        "DiType" : 3,
    },
    "Falns183" : {
        "Weight": 24,
        "BTT": 2,
        "BPT": 1,
        "BCT": 7,
        "isWagon": True,
        "DiType" : 3,
    },
    "Gbs254" : {
        "Weight": 13,
        "BTT": 2,
        "BPT": 1,
        "BCT": 7,
        "isWagon": True,
        "DiType" : 3,
    },
    "Habbins" : {
        "Weight": 27,
        "BTT": 1, # G/P_Brake selector
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Habbiins" : {
        "Weight": 27,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Habbiins344" : {
        "Weight": 27,
        "BTT": -1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 0,
    },
    "Kijls" : {
        "Weight": 17,
        "BTT": 3, # BrakeSelector
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 2,
    },
    "Rmms663" : {
        "Weight": 21,
        "BTT": 2,
        "BPT": 1,
        "BCT": 7,
        "isWagon": True,
        "DiType" : 3,
    },
    "Roos-t645" : {
        "Weight": 25,
        "BTT": -1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 0,

    },
    "Roos-t" : {
        "Weight": 25,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Shimmns-u" : {
        "Weight": 22,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Shimmns" : {
        "Weight": 22,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Shimmns-U708" : {
        "Weight": 22,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Shimmns-TTU722" : {
        "Weight": 24,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Tadgs" : {
        "Weight": 24,
        "BTT": 420,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Tadgs959" : {
        "Weight": 24,
        "BTT": 420,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Uacns82" : {
        "Weight": 18,
        "BTT": -1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 0,
    },
    "Zacns" : {
        "Weight": 23,
        "BTT": 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Laaers" : {
        "Weight": 30,
        "BTT" : 1,
        "BPT": 1,
        "BCT": 1,
        "isWagon" : True,
        "DiType" : 1,
    },
    "Sggmrss" : {
        "Weight" : 30,
        "BTT" : 1,
        "BPT" : 1,
        "BCT" : 1,
        "isWagon" : True ,
        "DiType" : 1,

    },
    "ABnb-703": {
        "Weight": 35,
        "BTT": 14,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Avmz" : {
        "Weight": 50,
        "BTT": 11,
        "BPT": 1,
        "BCT": 2,
        "isWagon": True,
        "DiType" : 5,
    },
    "Bmmz" : {
        "Weight": 50,
        "BTT": 11,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bmmdz" : {
        "Weight": 45,
        "BTT": 11,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bmmbz" : {
        "Weight": 50,
        "BTT": 11,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bmz" : {
        "Weight": 55,
        "BTT": 11,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bnb-719" : {
        "Weight" : 35,
        "BTT" : 14,
        "BPT":  1,
        "BCT" : 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bnr" : {
        "Weight": 40,
        "BTT": 12,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bnrdfz" : {
        "Weight": 40,
        "BTT": 12,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bnrdzf" : {
        "Weight": 40,
        "BTT": 12,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "Bpmmbdzf" : {
        "Weight": 55,
        "BTT": 11,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 5,
    },
    "Bpmz" : {
        "Weight": 50,
        "BTT": 11,
        "BPT": 1,
        "BCT": 2,
        "isWagon": True,
        "DiType" : 5,
    },
    "Byg516" : {
        "Weight": 35,
        "BTT": 15,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "766pbzfa" : {
        "Weight": 60,
        "BTT": 13,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "785pza" : {
        "Weight": 60,
        "BTT": 13,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },
    "780pza" : {
        "Weight": 60,
        "BTT": 13,
        "BPT": 1,
        "BCT": 1,
        "isWagon": True,
        "DiType" : 1,
    },

    }
